language: csharp
mono: none
dotnet: 1.1.5
dist: trusty
solution: Bearded.Monads.sln
install:
 - dotnet restore Bearded.Monads.sln
before_script:
 - dotnet build Bearded.Monads.sln
 - dotnet test ./Bearded.Monads.Tests/Bearded.Monads.Tests.csproj
 - dotnet pack /p:PackageVersion=$MAJOR.$MINOR.$TRAVIS_BUILD_NUMBER -o ../ ./Bearded.Monads/Bearded.Monads.csproj
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.1.5
script:
 - dotnet nuget push -s https://www.nuget.org/api/v2/package -k $API_KEY ./Bearded.Monads.$MAJOR.$MINOR.$TRAVIS_BUILD_NUMBER.nupkg
branches:
  only:
  - master
